"""Constants for the Smart-me integration."""

DOMAIN = "smartme"

CONF_DEVICES = "devices"

API_BASE_URL = "https://api.smart-me.com"

# Cloud API - don't poll too aggressively.
DEFAULT_SCAN_INTERVAL = 300  # seconds

# MeterEnergyType, as returned by the smart-me API (device["deviceEnergyType"])
ENERGY_TYPE_UNKNOWN = 0
ENERGY_TYPE_ELECTRICITY = 1
ENERGY_TYPE_WATER = 2
ENERGY_TYPE_GAS = 3
ENERGY_TYPE_HEAT = 4
ENERGY_TYPE_HCA = 5
ENERGY_TYPE_ALL_METERS = 6
ENERGY_TYPE_TEMPERATURE = 7
ENERGY_TYPE_MBUS_GATEWAY = 8
ENERGY_TYPE_RS485_GATEWAY = 9
ENERGY_TYPE_CUSTOM_DEVICE = 10
ENERGY_TYPE_COMPRESSED_AIR = 11
ENERGY_TYPE_SOLAR_LOG = 12
ENERGY_TYPE_VIRTUAL_METER = 13

# MeterSubType, as returned by the smart-me API (device["meterSubType"])
SUB_TYPE_UNKNOWN = 0
SUB_TYPE_COLD_WATER = 1
SUB_TYPE_HOT_WATER = 2
SUB_TYPE_CHARGING_STATION = 3
SUB_TYPE_ELECTRICITY = 4
SUB_TYPE_WATER = 5
SUB_TYPE_GAS = 6
SUB_TYPE_ELECTRICITY_HEAT = 7
SUB_TYPE_TEMPERATURE = 8
SUB_TYPE_VIRTUAL_BATTERY = 9
